---
version: 0.1
n9e:
  url:
    base: http://192.168.31.174:11180
    rdb: http://192.168.31.174:11180
  token: 9be48eb68cba192a365a290c7cbeb310

pollings:
- task: "aliyun_ac_metric"
  type: metric
  regions:
  - name: cn-beijing
  credentials:
    key:      XXXXXX
    secret:   XXXXXX
  vendor:  aliyun
  version: 1.0
  interval: 60
  nodes:
  - componentId: metric-1
    nodeType: metric
    action: query
    vars:
      metaName: CPUUtilization
      namespace: acs_ecs_dashboard
    target:
      metric: cpu_utils
      endpoint: vm.instanceId
      timestamp: vm.timestamp
      step: 60
      value: vm.value
      dstype: percentage
  - componentId: metric-2
    nodeType: metric
    action: query
    vars:
      metaName: DiskReadBPS
      namespace: acs_ecs_dashboard
    target:
      metric: disk_read
      endpoint: vm.instanceId
      timestamp: vm.timestamp
      step: 60
      value: vm.value
      dstype: byteps
  - componentId: metric-3
    nodeType: metric
    action: query
    vars:
      metaName: DiskReadIOPS
      namespace: acs_ecs_dashboard
    target:
      metric: disk_read_iops
      endpoint: vm.instanceId
      timestamp: vm.timestamp
      step: 60
      value: vm.value
      dstype: gauge
  - componentId: metric-4
    nodeType: metric
    action: query
    vars:
      metaName: DiskWriteBPS
      namespace: acs_ecs_dashboard
    target:
      metric: disk_write
      endpoint: vm.instanceId
      timestamp: vm.timestamp
      step: 60
      value: vm.value
      dstype: byteps
  - componentId: metric-5
    nodeType: metric
    action: query
    vars:
      metaName: DiskWriteIOPS
      namespace: acs_ecs_dashboard
    target:
      metric: disk_write_iops
      endpoint: vm.instanceId
      timestamp: vm.timestamp
      step: 60
      value: vm.value
      dstype: gauge
  - componentId: metric-6
    nodeType: metric
    action: query
    vars:
      metaName: IntranetInRate
      namespace: acs_ecs_dashboard
    target:
      metric: intranet_in
      endpoint: vm.instanceId
      timestamp: vm.timestamp
      step: 60
      value: vm.value
      dstype: bitps
  - componentId: metric-7
    nodeType: metric
    action: query
    vars:
      metaName: IntranetOutRate
      namespace: acs_ecs_dashboard
    target:
      metric: intranet_out
      endpoint: vm.instanceId
      timestamp: vm.timestamp
      step: 60
      value: vm.value
      dstype: bitps
  - componentId: metric-8
    nodeType: metric
    action: query
    vars:
      metaName: InternetInRate
      namespace: acs_ecs_dashboard
    target:
      metric: internet_in
      endpoint: vm.instanceId
      timestamp: vm.timestamp
      step: 60
      value: vm.value
      dstype: bitps
  - componentId: metric-9
    nodeType: metric
    action: query
    vars:
      metaName: InternetOutRate
      namespace: acs_ecs_dashboard
    target:
      metric: internet_out
      endpoint: vm.instanceId
      timestamp: vm.timestamp
      step: 60
      value: vm.value
      dstype: bitps
- task: "aliyun_ac_res"
  regions:
  - name: cn-beijing
  - name: cn-shanghai
  - name: cn-zhangjiakou
  - name: cn-hangzhou
  - name: cn-qingdao
  credentials:
    key:      XXXXXXXX
    secret:   XXXXXXXX
  vendor:  aliyun
  version: 1.0
  timeout: 1800
  interval: 120
  nodes:
  - componentId: instance-1
    nodeType: instance
    action: list
    target:
      name: vm.name
      uuid: vm.providerId
      ident: vm.providerId
      extend:
        imageId: vm.imageId
        instanceChargeType: vm.instanceChargeType
        flavorId: vm.flavorId
        status: vm.status
        securityGroups: vm.securityGroups
        internetChargeType: vm.internetChargeType
        keyPairName: vm.keyPairName
        vpcId: vm.vpcId
        vSwitchId: vm.vSwitchId
        floatingIp: vm.floatingIp
        eipAddress: vm.eipAddress
        primaryIp: vm.primaryIp
        expiredAt: vm.expiredAt
        stoppedMode: vm.stoppedMode
        osName: vm.osName
        osType: vm.osType
        cpu: vm.cpu
        memory: vm.memory
      labels:
        regionId: vm.regionId
        osType: vm.osType
        platform: aliyun
      cate: "vegaops-vm"
      nid: 12
  - componentId: vpc-1
    nodeType: vpc
    action: list
    target:
      name: vm.vpcName
      uuid: vm.providerId
      ident: vm.providerId
      extend:
        status: vm.status
        cidrBlock: vm.cidrBlock
      labels:
        regionId: vm.regionId
        platform: aliyun
      cate: "vegaops-vpc"
      nid: 12
  - componentId: subnet-1
    nodeType: vswitch
    action: list
    target:
      name: vm.name
      uuid: vm.providerId
      ident: vm.providerId
      extend:
        status: vm.status
        cidrBlock: vm.cidrBlock
        vpcId: vm.vpcId
      labels:
        regionId: vm.regionId
        platform: aliyun
      cate: "vegaops-subnet"
      nid: 12
